server:
  port: 1030
spring:
  application:
    name: movie-server
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///itsource-move?useUnicode=true&characterEncoding=utf8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848	#注册中心地址
    sentinel:
      transport:
        dashboard: localhost:1111
mybatis:
  type-aliases-package: com.xzz.*.domain,com.xzz.*.query,com.xzz.*.dto
feign:
  sentinel:
    enabled: true #熔断